### ISSUE TITLE
Add a function for get City from state

### ISSUE THREAD

**Issue by tejas14894** [SwapnilNakhate/Cities-States-Country#1]
Hello Swapnil,

Cities-States-Country package having all function to get the state from country but, not the city from state.
Because, use of  search city function taking time and the UI gets stucked a bit.
Can you please add the  function to get city from state?

Thanks in advance,
Tejas Patil

**Comment by SwapnilNakhate** [comment]
Hi Tejas, I have updated package with two functions :
